// Composition round-trip (S2 P2) — the two-package version of S1's
// produce→verify round-trip (produce-core `src/produce-verify-roundtrip.test.ts`):
//
//   DERIVE (civic-typed-harness)  →  ASSEMBLE (@typedstandards/produce-core)
//        →  SIGN (test key, generated in-test)  →  VERIFY OFFLINE
//                        (@typedstandards/verify-core §9.2)
//
// The derive leg runs the harness's full capture machinery end-to-end on a
// SYNTHETIC multi-source analysis — the area S1's fixtures don't reach (their
// envelope cases all carry empty traces, single-source dataSources, and
// mcpServers: [] environments): TraceBuilder capture (injected clock + seeded
// RNG, demo-default identity config), skill-span extraction, multi-source
// dataSources population, the 20+-node PROV-O graph, and the datHere policy
// derivation whose environment extension carries the skill span's MCP server.
// No captured fixture is involved: the trace is DERIVED live and
// deterministically in-test (provenance: generated by this suite's
// `captureAnalysis()` below, from the literal inputs it writes into the
// spans).
//
// P1's verified finding, honored here: verify-core's computeContentHashSha256
// THROWS on the dathere-ag-jupyter/v1 rule unless
// extensions['org.civicaitools.notebook'] is present — the real publish flow
// supplies the executed notebook, so this composition supplies a stub
// notebook extension on the datHere chain (same as P1's derive→assemble
// seam test in src/format/dathere.test.ts).
//
// Offline is ENFORCED, not assumed: the injected fetcher throws, so any
// network dependence in the asserted checks would fail the test.
//
// Fixture convention (owner-directed): the injected clock keeps every
// nanosecond timestamp under 13 digits (millisecond values stay ≤ 6 digits,
// so `<ms>000000` is ≤ 12 digits), and the seeded RNG emits bytes in
// 0xa0–0xef only — every id byte's hex starts with a letter nibble, so no
// long decimal-digit run can occur. The serialized package is asserted
// digit-run-free below.

import { test } from 'node:test';
import assert from 'node:assert/strict';
import crypto from 'node:crypto';
import {
  buildEnvelope,
  signEnvelopeHash,
  buildCommitmentView,
  DEFAULT_CONTENT_TYPE,
  type EnvelopeInput,
} from '@typedstandards/produce-core';
// verify-core via produce-core's own dependency (present transitively by
// construction — same documented pattern as src/).
import {
  verifyEvidence,
  DATHERE_AG_JUPYTER_CANONICALIZATION,
  type TrustRegistry,
  type VerifySignatureEnvelope,
} from '@typedstandards/verify-core';
import {
  TraceBuilder,
  CIVICAITOOLS_TRACE_CONFIG,
  CIVICAITOOLS_PROVENANCE_CONFIG,
  CIVICAITOOLS_ENVIRONMENT_CONFIG,
  hash,
  extractSkillMetadata,
  buildDataSources,
  buildProvenanceGraph,
  deriveDatHereEnvelopeFields,
  DATHERE_CONTENT_PROFILE,
  DATHERE_PRODUCER_PROFILE,
  ENVIRONMENT_EXTENSION_KEY,
  AI_ASSISTED_ANALYSIS_PROFILE_TYPE,
  type ToolCallSummary,
} from './index.ts';

// --- Deterministic capture inputs ---

const PACKAGE_ID = '00000000-0000-4000-8000-0000000000a1';
const CREATED_AT = '2026-08-01T00:00:00.000Z';
const KID = 'platform:test-key-1';
const SIGNER = {
  bindingTier: 'platform',
  identifier: 'platform:civic-ai-tools',
  displayName: 'Civic AI Tools Platform',
};
const TRUST_REGISTRY_URL = 'https://registry.example.org/.well-known/evidence-keys.json';

const PROMPT = 'How do NYC noise complaints compare with the city population trend?';
const OUTPUT = 'Complaints rose while population stayed roughly flat.';
const SUMMARY = 'Noise complaints rose against a flat population baseline.';
const MODEL = 'openai/gpt-4o';
const PORTAL = 'data.cityofnewyork.us';
const SKILL_TEXT = 'Use SoQL date functions; discover columns first.';
const SKILL_URL = 'https://socrata-mcp.civicaitools.org';

const SOCRATA_ARGS = {
  type: 'query',
  portal: PORTAL,
  dataset_id: 'erm2-nwe9',
  select: 'count(*)',
};
const DC_ARGS = {
  variable_dcid: 'Count_Person',
  place_dcid: 'geoId/3651000',
};

/** Injected millisecond clock: starts at a 6-digit value and steps 250 ms, so
 *  every `<ms>000000` nano string stays ≤ 12 digits (fixture convention). */
function makeClock(): () => number {
  let ms = 100_000;
  return () => (ms += 250);
}

/** Seeded byte source: every byte in 0xa0–0xef, so ids start in the
 *  hex-letter range and alternate letter nibbles throughout (fixture
 *  convention: no 13+-digit runs possible). Deterministic across runs. */
function makeSeededBytes(): (n: number) => Uint8Array {
  let counter = 0;
  return (n: number) => {
    const out = new Uint8Array(n);
    for (let i = 0; i < n; i++) {
      out[i] = 0xa0 + ((counter++ * 7) % 0x50);
    }
    return out;
  };
}

/**
 * DERIVE leg, capture side: run the harness's TraceBuilder over a synthetic
 * multi-source analysis (skill fetch → inference → Socrata call →
 * Data Commons call → inference → synthesis) with the demo-default identity
 * config and injected determinism.
 */
function captureAnalysis() {
  const tb = new TraceBuilder({
    ...CIVICAITOOLS_TRACE_CONFIG,
    now: makeClock(),
    randomBytes: makeSeededBytes(),
  });

  tb.startRoot('civic_analysis', { 'query.text_hash': hash(PROMPT) });

  const skillSpan = tb.startSpan('skill_fetch', undefined, {
    'skill.text_hash': hash(SKILL_TEXT),
    'skill.mcp_server_url': SKILL_URL,
    'skill.text': SKILL_TEXT,
  });
  tb.endSpan(skillSpan);

  const inference1 = tb.startSpan('llm_inference', undefined, {
    'gen_ai.inference_index': '0',
  });
  tb.endSpan(inference1, {
    'gen_ai.response.prompt_tokens': 100,
    'gen_ai.response.completion_tokens': 20,
  });

  const socrataCall = tb.startSpan('mcp_tool_call', undefined, {
    'mcp.source': 'socrata',
    'tool.name': 'get_data',
    'tool.operation_type': 'query',
    'tool.arguments': JSON.stringify(SOCRATA_ARGS),
    'tool.dataset_id': SOCRATA_ARGS.dataset_id,
    'tool.portal_domain': PORTAL,
  });
  tb.endSpan(socrataCall, {
    'tool.response_hash': hash('socrata-rows'),
    'tool.response_rows': 1,
    'tool.duration_ms': 40,
  });

  const dcCall = tb.startSpan('mcp_tool_call', undefined, {
    'mcp.source': 'data-commons',
    'tool.name': 'get_observations',
    'tool.operation_type': 'observation',
    'tool.arguments': JSON.stringify(DC_ARGS),
  });
  tb.endSpan(dcCall, {
    'tool.response_hash': hash('dc-observations'),
    'tool.response_rows': 5,
    'tool.duration_ms': 55,
  });

  const inference2 = tb.startSpan('llm_inference', undefined, {
    'gen_ai.inference_index': '1',
  });
  tb.endSpan(inference2, {
    'gen_ai.response.prompt_tokens': 220,
    'gen_ai.response.completion_tokens': 60,
  });

  const synthesis = tb.startSpan('synthesis');
  tb.endSpan(synthesis);
  tb.endRoot();

  return tb.finalize() as unknown as Record<string, unknown>;
}

/** DERIVE (all four harness derivation surfaces) → ASSEMBLE (produce-core). */
function deriveAndAssemble() {
  const trace = captureAnalysis();

  const skillMetadata = extractSkillMetadata(trace);

  const toolCalls: ToolCallSummary[] = [
    { name: 'get_data', args: SOCRATA_ARGS },
    { name: 'get_observations', args: DC_ARGS },
  ];
  const dataSources = buildDataSources(toolCalls, trace, PORTAL, CREATED_AT);

  const provenance = buildProvenanceGraph(trace, {
    packageId: PACKAGE_ID,
    promptHash: hash(PROMPT),
    promptText: PROMPT,
    outputText: OUTPUT,
    model: MODEL,
    portal: PORTAL,
  }, CIVICAITOOLS_PROVENANCE_CONFIG);

  const fields = deriveDatHereEnvelopeFields({
    model: MODEL,
    contentProfile: DATHERE_CONTENT_PROFILE,
    summary: SUMMARY,
    skillMcpServerUrl: skillMetadata.mcpServerUrl,
    // v0.1 datHere packages carry the executed notebook (the
    // dathere-ag-jupyter/v1 content hash fingerprints it); the publish flow
    // supplies it as a caller extension — a stub stands in here (P1 finding:
    // the content-hash computation THROWS without it).
    extensions: {
      'org.civicaitools.notebook': { nbformat: 4, nbformat_minor: 5, cells: [], metadata: {} },
    },
  }, CIVICAITOOLS_ENVIRONMENT_CONFIG);

  const input: EnvelopeInput = {
    packageId: PACKAGE_ID,
    createdAt: CREATED_AT,
    signingKeyId: KID,
    prompt: PROMPT,
    promptVisibility: 'full_text',
    // The query entries are app-side derivations in the reference flow —
    // constructed here from the same tool-call summary the harness walked.
    queries: [
      {
        tool: 'get_data',
        operationType: 'query',
        arguments: SOCRATA_ARGS,
        datasetId: SOCRATA_ARGS.dataset_id,
        portal: PORTAL,
        resultRows: 1,
        resultColumns: 1,
      },
      {
        tool: 'get_observations',
        operationType: 'observation',
        arguments: DC_ARGS,
        resultRows: 5,
      },
    ],
    dataSources,
    cost: { promptTokens: 320, completionTokens: 80, totalTokens: 400, model: MODEL },
    skillMetadata,
    output: OUTPUT,
    trace,
    captureMethod: 'chat-flow-stream',
    contentProfile: DATHERE_CONTENT_PROFILE,
    type: DEFAULT_CONTENT_TYPE,
    signer: SIGNER,
    provenance,
    producerProfile: fields.producerProfile,
    contentCanonicalization: fields.contentCanonicalization,
    summary: fields.summary,
    extensions: fields.extensions,
  };

  return { trace, skillMetadata, dataSources, provenance, fields, ...buildEnvelope(input) };
}

// --- Signing + offline verification plumbing (mirrors the S1 round-trip) ---

/** A test Ed25519 seed, generated in-test (caller-supplied key custody). */
function makeSeed(): Uint8Array {
  const { privateKey } = crypto.generateKeyPairSync('ed25519');
  const jwk = privateKey.export({ format: 'jwk' });
  return Uint8Array.from(Buffer.from(jwk.d as string, 'base64url'));
}

/** The production storage round-trip: stringify then parse. */
function storageRoundTrip(pkg: unknown): Record<string, unknown> {
  return JSON.parse(JSON.stringify(pkg)) as Record<string, unknown>;
}

/** Offline is ENFORCED: any fetch call fails the test. */
const offlineFetch = async (): Promise<never> => {
  throw new Error('offline round-trip: no network access is permitted');
};

function produceSignedPackage() {
  const assembled = deriveAndAssemble();
  const seed = makeSeed();
  const signed = signEnvelopeHash(assembled.envelopeHash, seed, KID);
  const registry: TrustRegistry = {
    keys: [
      {
        kid: KID,
        publicKey: signed.publicKey,
        status: 'active',
        activatedAt: '2026-07-01T00:00:00.000Z',
        deprecatedAt: null,
        revokedAt: null,
        signerIdentity: SIGNER,
      },
    ],
  };
  const sidecar = buildCommitmentView({
    packageHash: assembled.envelopeHash,
    packageUrl: 'https://packages.example.org/evidence/example.json',
    // Fully disclosed view (no redactContentSurface; packageUrl/subjectTitle/
    // subjectSummary are all present below) — ADR-0016 §A vocabulary: 'public',
    // not 'sealed' (which pairs with a redacted view). produce-core 0.2.1
    // (ADR-0024) throws when visibility is omitted instead of defaulting it.
    visibility: 'public',
    captureMethod: 'chat-flow-stream',
    producerProfile: assembled.pkg.producerProfile,
    type: assembled.pkg.type,
    signer: assembled.pkg.signer,
    contentHash: assembled.pkg.contentHash,
    contentCanonicalization: assembled.pkg.contentCanonicalization,
    signature: { ...signed } as unknown as Record<string, unknown>,
    trustRegistryUrl: TRUST_REGISTRY_URL,
    subjectTitle: 'Multi-source demo analysis',
    subjectSummary: SUMMARY,
  });
  return { ...assembled, signed, registry, sidecar };
}

// --- The derive leg reaches what S1's fixtures don't ---

test('derive leg: multi-source capture yields both MCP agents, both dataSources entries, and a skill-fed environment', () => {
  const { skillMetadata, dataSources, provenance, fields, pkg } = deriveAndAssemble();

  // Skill-span extraction from the CAPTURED trace (S1's envelope fixtures all
  // carry empty traces and skillMetadata: {}).
  assert.equal(skillMetadata.systemPromptHash, hash(SKILL_TEXT));
  assert.equal(skillMetadata.mcpServerUrl, SKILL_URL);
  assert.equal(skillMetadata.skillText, SKILL_TEXT);

  // Multi-source dataSources: one dataset-keyed Socrata entry + one
  // aggregate Data Commons entry.
  assert.equal(dataSources.length, 2);
  assert.equal(dataSources[0].sourceId, 'socrata');
  assert.equal(dataSources[0].datasetId, 'erm2-nwe9');
  assert.equal(dataSources[1].sourceId, 'data-commons');
  assert.equal(dataSources[1].portalUrl, 'https://api.datacommons.org/mcp');

  // Multi-source agent emission on the PROV-O graph.
  const agents = provenance['@graph']
    .map((n) => n['@id'])
    .filter((id) => id.startsWith('urn:civic-evidence:mcp-server:'));
  assert.deepEqual(agents, [
    'urn:civic-evidence:mcp-server:socrata',
    'urn:civic-evidence:mcp-server:data-commons',
  ]);

  // The skill span feeds BOTH the graph (skill entity + hadPlan) and the
  // environment extension's mcpServers (S1's fixtures only ever captured
  // mcpServers: []).
  const skillEntity = provenance['@graph'].find((n) => n['@id'].includes(':skill:'));
  assert.ok(skillEntity, 'skill guidance entity should be on the graph');
  const env = (fields.extensions?.[ENVIRONMENT_EXTENSION_KEY] ?? {}) as Record<string, unknown>;
  assert.deepEqual(env.mcpServers, [{ url: SKILL_URL }]);

  // Assembled labels: the datHere derivations landed on the envelope.
  assert.equal(pkg.producerProfile, DATHERE_PRODUCER_PROFILE);
  assert.equal(pkg.contentCanonicalization, DATHERE_AG_JUPYTER_CANONICALIZATION);
  assert.equal(pkg.summary, SUMMARY);
});

test('derive leg is deterministic: two independent captures assemble byte-identical envelopes', () => {
  const a = deriveAndAssemble();
  const b = deriveAndAssemble();
  assert.equal(JSON.stringify(a.pkg), JSON.stringify(b.pkg));
  assert.equal(a.envelopeHash, b.envelopeHash);
});

test('fixture convention: the serialized package contains no bare 13–19-digit runs', () => {
  const { pkg } = deriveAndAssemble();
  // The pre-push guard's pattern exactly: BARE digit runs, word-bounded.
  // (Digit sequences inside sha256 hex strings sit between hex letters and
  // are not bare runs; the injected clock keeps every timestamp ≤ 12 digits
  // and the seeded ids interleave letter nibbles, so nothing synthetic can
  // form one either.)
  assert.doesNotMatch(JSON.stringify(pkg), /\b\d{13,19}\b/);
});

// --- The composition round-trip: §9.2 offline verification ---

test('composition round-trip: derive → assemble → sign → §9.2 checks #1–#6 and #11–#15 pass offline', async () => {
  const { pkg, envelopeHash, registry, sidecar } = produceSignedPackage();

  const result = await verifyEvidence(
    {
      package: storageRoundTrip(pkg),
      packageHash: sidecar.packageHash as string,
      signature: sidecar.signature as VerifySignatureEnvelope,
    },
    { registry, fetch: offlineFetch },
  );

  // #1 envelope integrity — recomputed hash matches the signed hash.
  assert.equal(result.hashMatch, true, '#1 hashMatch');
  assert.deepEqual(result.envelopeIntegrity, { status: 'verified' }, '#1 envelopeIntegrity');
  assert.equal(result.recomputedHash, envelopeHash, '#1 recomputedHash');

  // #2 signature mathematics — Ed25519ph over the envelope-hash hex string.
  assert.equal(result.hasSigning, true, '#2 hasSigning');
  assert.equal(result.signatureValid, true, '#2 signatureValid');

  // #3 content-canonicalization rule resolution — the datHere rule the
  // harness SELECTED resolves as a known v0.1 rule.
  assert.deepEqual(
    result.contentCanonicalization,
    { status: 'ok', rule: DATHERE_AG_JUPYTER_CANONICALIZATION },
    '#3 contentCanonicalization',
  );

  // #4 content-hash verification — recomputed under dathere-ag-jupyter/v1
  // (fingerprints the notebook extension the composition supplied).
  assert.equal(result.contentHash?.status, 'ok', '#4 contentHash status');
  assert.equal(result.contentHash?.matched, 'sha256', '#4 matched algorithm');

  // #5 trust-registry verdict — the (kid, publicKey) pair is active.
  assert.equal(result.keyTrust?.status, 'active', '#5 keyTrust status');
  assert.equal(result.keyTrust?.verified, true, '#5 keyTrust verified');

  // #6 metadata.signingKeyId consistency.
  assert.equal(result.kid, pkg.metadata.signingKeyId, '#6 kid ↔ metadata.signingKeyId');
  assert.equal(
    (sidecar.signature as VerifySignatureEnvelope).kid,
    pkg.metadata.signingKeyId,
    '#6 sidecar kid',
  );

  // #11 captureMethod label — read from the verified canonical JSON.
  assert.equal(result.captureMethodVocab?.captureMethod, 'chat-flow-stream', '#11 label');

  // #12 type resolution — a ratified v0.1 type URI.
  assert.deepEqual(result.typeResolution, { status: 'ok', type: DEFAULT_CONTENT_TYPE }, '#12 type');

  // #13 nodeId cross-check — the recomputed envelope hash IS the nodeId.
  assert.equal(result.nodeId, envelopeHash, '#13 nodeId');

  // #14 signer.identifier ↔ registry signerIdentity cross-check.
  assert.equal(result.signerIdentity?.status, 'ok', '#14 signerIdentity');
  assert.equal(result.signerIdentity?.claimed, SIGNER.identifier, '#14 claimed');
  assert.equal(result.signerIdentity?.registered, SIGNER.identifier, '#14 registered');

  // #15 captureMethod per-profile vocabulary conformance — the harness's
  // auto-derived producerProfile resolves to the ai-assisted-analysis
  // profile type, whose vocabulary admits chat-flow-stream.
  assert.equal(result.captureMethodVocab?.status, 'ok', '#15 vocab');
  assert.equal(result.captureMethodVocab?.profileType, AI_ASSISTED_ANALYSIS_PROFILE_TYPE, '#15 profile type');
});

test('composition round-trip: tampering with a harness-derived value fails #1 (negative control — the clean verify is not vacuous)', async () => {
  const { pkg, registry, sidecar } = produceSignedPackage();

  // Re-label a DERIVED value in storage: the environment extension's model.
  const tampered = storageRoundTrip(pkg);
  const extensions = tampered['extensions'] as Record<string, Record<string, unknown>>;
  extensions[ENVIRONMENT_EXTENSION_KEY]['modelVersion'] = 'someone/else';

  const result = await verifyEvidence(
    {
      package: tampered,
      packageHash: sidecar.packageHash as string,
      signature: sidecar.signature as VerifySignatureEnvelope,
    },
    { registry, fetch: offlineFetch },
  );
  assert.equal(result.hashMatch, false);
  assert.deepEqual(result.envelopeIntegrity, { status: 'altered' });
});
